### ISSUE TITLE
[FEAT] 프로필, 매칭 관련 TODO 구현 진행

### ISSUE THREAD

**Issue by LeeHusung** [goaheadgogo/backend#67]
### 📝 기능 설명

- 코드 중복 제거, 불필요한 코드 존재 검사
- 프로필 등록 후 매칭 리스트에 등록 기능 추가
  - 우선 프로필 등록 시에는 매칭리스트에 등록 동시에 못하게 했고, 이후 프로필 등록과 동시에 매칭리스트에 등록하게끔 변경 가능할 수 도 있음. 현재는 프로필 등록 완료 이후 따로 버튼을 통해 등록/해제 로 구현
  
- 프로필 이미 등록되어있을 시 , 중복 등록 검증 추가
- 대기 or 수락중인 매칭 존재 시 프로필 삭제 불가 기능 추가
  - 처음에 신청 보내면 "PENDING" 
    - 이후 상대가 수락하면 "ACCEPTED"
    - 내가 신청 취소하면 "CANCELED"
    - 수락 이후 채팅 and 계약 진행 후 완료하고 싶으면 or 합의가 안돼서 현재 매칭 그만 진행하고 싶으면 완료버튼 누르고 "COMPLETED"   => 여기 논의해봐야함. 복잡하다. 채팅까지만 하면 괜찮겠는데 계약, 결제까지 가면, 매칭의 어느 단계(수락, 채팅, 계약 등)에 있을 때 프로필 삭제가 불가능하게 할건지?
    - 우선 IN_PROGRESS_CONTRACT 계약 진행 중일 시에만 삭제 불가능하도록 진행함.

- 운영 전까지 개발, 테스트 용이성을 위해 휴대폰 본인인증은 추후에 진행하겠습니다.

### 작업 내용

- [x] 코드 중복 제거, 불필요한 코드 존재 검사

- [x] 프로필 등록 후 매칭 리스트에 등록 기능 추가

- [x] 대기중인 매칭 존재 시 프로필 삭제 불가 기능 추가 - 삭제 가능 기준 논의 필요

### ⏳ 추정 시간

2
